Update minetet server to 5.9.0 - add cap_perms mod + tutorial game
minetest4scrum/minetest-docker-wrapper pull request #1
Opened 2024-09-03 17:37 UTC by KimRagnaSchwerdt

Update minetest server to 5.9.0
add minetest_game as git submodule
add tutorial from ContentDB
fix init script for environment variable replacement
add cap_perms mod

2024-09-03 17:38 UTC, KimRagnaSchwerdt commented
local testing is still pending

2024-09-04 07:27 UTC, Dav-Git requested changes
1 kleiner Change, sonst sieht es gut aus

2024-09-04 07:27 UTC, Dav-Git commented on games/tutorial/.mailmap
> +Wuzzy <Wuzzy@disroot.org> <almikes@aol.com>
Was ist denn das?

2024-09-04 07:27 UTC, Dav-Git commented on mods/cap_perms/init.lua
> +-- Author: David Bauch
Hier Torben S eintragen :)

2024-09-04 11:43 UTC, KimRagnaSchwerdt commented on mods/cap_perms/init.lua
> +-- Author: David Bauch
Danke für die Hinweise

2024-09-04 12:02 UTC, Dav-Git approved these changes

2024-09-09 11:21 UTC, minetest4scrum approved these changes
OK

2024-09-09 11:21 UTC, merged